### ISSUE TITLE
Error trying SauceNao

### ISSUE THREAD

**Issue by Lorhelei** [jacklul/e621-Batch-Reverse-Search#10]
While testing some images, I found two interesting things.

First is that you dind't consider when the extension is on capitals: eg: ".JPG". 

And the second I couldn't know what was it about. I'm no good with web things, sorry. But there is the debug log.

[debug_error.txt](https://github.com/jacklul/e621-Batch-Reverse-Search/files/1977075/debug_error.txt)

The interesting part is that only happens with some images and when going through saucenao.

**Comment by jacklul** [comment]
Capitalized file extension issue - fixed.

About soucenow: their results page is a bit tricky to parse and pull the data from, limited it to pulling e621 links only.

**Comment by Lorhelei** [comment]
Oush, I was trying to get pixiv and deviant art files for a batch downloader using the html that your apps leave, hehe.

Thanks for the quick reply thou.
