### ISSUE TITLE
"Daily Search Limit Exceeded" on SauceNAO

### ISSUE THREAD

**Issue by ghost** [jacklul/e621-Batch-Reverse-Search#11]
`Daily Search Limit Exceeded.`
`***.***.***.***, your IP has exceeded the unregistered user's daily limit of 150 searches.`

If the SauceNAO option is enabled and the count of images that is displayed after "Scanning for images..." is over 150, it should display some kind of message that users can disable, warning them about the 150 picture daily limit.

**Comment by Lorhelei** [comment]
It only happens if the count is over 150? I think I did over 3 searches of 70 images and didn't receive that message.

**Comment by jacklul** [comment]
https://github.com/jacklul/e621-Batch-Reverse-Search/releases/tag/1.3.2

To avoid limits either change IP (proxy, VPN, modem reset etc) or register an account and use API key (raises limit to 300 requests per 24 hours).

There are some limits per 30 seconds as well, around 20 requests per second, I think it should be fine in most cases but when it happens script should sleep for 1 minute to replenish that limit pool.

**Comment by ghost** [comment]
Okay, I'll keep that in mind.
Thanks again.
