### ISSUE TITLE
Use of more databases

### ISSUE THREAD

**Issue by Lorhelei** [jacklul/e621-Batch-Reverse-Search#12]
Is there any plans to implement another reverse search engine, like iqdb for example?

Since SauceNAO has a relatively small limit and the other engine usually isn't that useful.

**Comment by jacklul** [comment]
If you know of any other services feel free to suggest them.

**Comment by Lorhelei** [comment]
I would say:

-iqdb
-ninja.cure
-Google search
-TinEye

But the last two can be too tricky, but ninja cure has its own api, I don't know about iqdb though. Sorry for the late reply, hehe.

**Comment by jacklul** [comment]
I've used regular iqdb in the past, it was really bad when it comes to e621 content.

Using Google image search would be pain the ass, it produces a lot of bad results (mostly links to pages that no longer have searched image on them).

**Comment by ghost** [comment]
For the most part, I know Yandex.ru typically gives me good results, and
even knows what's in the picture to show pictures like it, even if it can't
find it. If Yandex has an API of some kind, it'd be worth looking into.

**Comment by jacklul** [comment]
To be honest, it now make more sense to start a new project because it's getting not e621 related now... The general idea was to output e621 links only.

**Comment by Lorhelei** [comment]
I was working on a batch downloader based on the links your app gives. So, if you do it for general, I'll try to support you as much as I could ^^
