### ISSUE TITLE
App doesn't control search rate on SauceNAO

### ISSUE THREAD

**Issue by HoloWise** [jacklul/e621-Batch-Reverse-Search#15]
Got to try the app after last fix and I noticed that the app throws an unhandled error on each iteration when it reaches SauceNAO's limits (Running with api key, basic account, 6 per 30 sec, 200 per 24h)

I checked your code and seems that JSON returned by SauceNAO changed a bit thus causing your app to completely ignore intended delays. 

if and elseif ~ line 1009 return false cuz current JSON returned by the site does not include "short_remaining". or "long_remaining".

Reaching 6 per 30s limit
![1](https://user-images.githubusercontent.com/36460595/71773671-2a865000-2f61-11ea-9d68-927aab60cbad.png)

Reaching  200 per 24h limit
![2](https://user-images.githubusercontent.com/36460595/71773673-2eb26d80-2f61-11ea-989f-2a73c402df68.png)

JSON returned after repeatedly reaching 6 per 30s limit
![3](https://user-images.githubusercontent.com/36460595/71773674-3245f480-2f61-11ea-89d0-3c44da6a747e.png)

**Comment by jacklul** [comment]
I guess it should be good now
