### ISSUE TITLE
Burst limit for SauceNAO, but not for e621 IQDB

### ISSUE THREAD

**Issue by ghost** [jacklul/e621-Batch-Reverse-Search#17]
There seems to be a function in this script that automatically waits out the 30 second burst limit. However, there doesn't seem to be one for the throttle that e621 implemented for their self-hosted IQDB recently. Would it be possible to add a "sleep" command of sorts between e621 IQDB requests? I keep getting "Throttled: Too many requests".

**Comment by jacklul** [comment]
Should be working in [version 1.6.0](https://github.com/jacklul/e621-Batch-Reverse-Search/releases/tag/1.6.0).
