### ISSUE TITLE
Where do i put the image folder?

### ISSUE THREAD

**Issue by Simon4s** [jacklul/e621-Batch-Reverse-Search#19]
I dont see an image folder in the zip.

**Comment by ghost** [comment]
You make a folder called images in the same folder as e621BRS.phar, and put
the images in it.

**Comment by Simon4s** [comment]
is e621BRS.phar = e621-Batch-Reverse-Search-master?

**Comment by ghost** [comment]
Yes. If you extract the folder from the zip file, then e621BRS.phar is in it.
![dopus_o2SN4C78SZ](https://user-images.githubusercontent.com/16302135/105279808-32f5fc80-5b5d-11eb-92d0-04f65fbf5fff.png)

**Comment by Simon4s** [comment]
How come my download is different?
![image](https://user-images.githubusercontent.com/73717072/105285265-06a0a700-5b82-11eb-974e-81afd1c551fc.png)

**Comment by Simon4s** [comment]
I see. Downloaded the proper zip file. Couldn't get Saucenao to work though.
