### ISSUE TITLE
SauceNao 

### ISSUE THREAD

**Issue by Simon4s** [jacklul/e621-Batch-Reverse-Search#20]
I have inserted the SauceNAO Api key 

![image](https://user-images.githubusercontent.com/73717072/105318628-bcbfbd00-5b91-11eb-8dcf-aacd0b754cfe.png)

**Comment by jacklul** [comment]
Seems to be working on my end, so there's definitely something wrong on yours.
Putting `DEBUG=true` and `LOGGING=true` (will generate log file) into the config might show some details but no promises.

**Comment by Simon4s** [comment]
I didnt remove the ";" lol. All good now. Sadly i was hoping to see title names instead of links.

**Comment by KonoVitoDa** [comment]
How did you solve it? I'm having the same issue.
