### ISSUE TITLE
error: Authentication required, check configuration!

### ISSUE THREAD

**Issue by FionaLH4E** [jacklul/e621-Batch-Reverse-Search#22]
I am encountering an issue when running the program and obtaining the following log:

```
[1/15] Searching '004.jpeg':
Trying md5 sum... no matching posts found!
Trying reverse search #1 (e621.net/iqdb_queries)... error: Authentication required, check configuration!
```

I have confirmed that my configuration is set up correctly:

```
DEBUG=true
LOGGING=true
E621_LOGIN='MyUsername'
E621_API_KEY='MyE621ApiKey'
SAUCENAO_API_KEY='MySauceNaoApiKey'
```
I was wondering if you could assist me in understanding why I am receiving this "Authentication required" error.

**Comment by FionaLH4E** [comment]
config file is incorrectly linked?

**Comment by jacklul** [comment]
Try not using single quote symbols, maybe they were parsed as part of the key - see debug log output

**Comment by FionaLH4E** [comment]
The issue with the missing config file has been resolved by changing the following code:
`if (isset($options['config'])) {
    $this->readConfig(realpath($options['config']));
} elseif (file_exists(ROOT . "/config.cfg")) {
    $this->readConfig(ROOT . "/config.cfg");
}
`

to

`if (isset($options['config'])) {
    $this->readConfig(realpath($options['config']));
} elseif (file_exists(ROOT . "/src/config.cfg")) {
    $this->readConfig(ROOT . "/src/config.cfg");
}
`

This change ensures that the default config file (config.cfg) is located in the /src folder, which is where it is expected to be found.

**Comment by jacklul** [comment]
You're not supposed to run it from the `src/app.php` file, you're supposed to use phar from the releases or build it yourself with `build.php`.

**Comment by FionaLH4E** [comment]
Got it. Thanks!
