### ISSUE TITLE
PHP Parse error:  syntax error

### ISSUE THREAD

**Issue by ghost** [jacklul/e621-Batch-Reverse-Search#3]
I'm not exactly a PHP programmer, but I do come across this error every time I try to use the `run.sh` script:
**`PHP Parse error:  syntax error, unexpected '.', expecting ',' or ';' in phar:///mnt/c/Users/Faux-Pa/Downloads/0/e621BRS.phar/app.php on line 60`**

**Comment by jacklul** [comment]
Does not happen to me on the newest version (both from repository and from release zip) - lubuntu PHP 5.6. 
Are you sure you have the latest version? 

Are you also running it with wine? Is it working OK in this case? 

I will need your OS, platform (32bit/64bit) and PHP version to investigate.

**Comment by ghost** [comment]
"Bash on Windows"  (something available in Windows 10's Programs and Features after you enabled "Developer Mode" in settings), 64-Bit, and `PHP 5.5.9-1ubuntu4.21 (cli)`

**Comment by jacklul** [comment]
This script wasn't tested with PHP5.5, as I stated in the readme PHP5.6 is recommended.

**Comment by ghost** [comment]
Closing issue because I have actually lost access to my Windows 10 computer that has "Bash on Windows". Possibility that I might re-open the issue if I can replicate the issue on my Lubuntu 16.04 server build using PHP >=5.6.
