### ISSUE TITLE
Windows: Looking for a file 'e621BRS.phar'

### ISSUE THREAD

**Issue by giff-h** [jacklul/e621-Batch-Reverse-Search#4]
On windows 10, with php5.6 x86 NTS, running `run.bat` whether from src\ or parent directory, results in this error:
`Could not open input file: C:\Users\hamstap85\Desktop\e621-Batch-Reverse-Search-master\src\/e621BRS.phar`

Edit: on Linux as well. Is there some build that I'm missing?

**Comment by jacklul** [comment]
Use the release version: https://github.com/jacklul/e621-Batch-Reverse-Search/releases

Files in `src/` directory must be build with `build.php` script, output will be in `build/` directory.

**Comment by giff-h** [comment]
Oh. Thanks!
