### ISSUE TITLE
Reverse search fails with no response from server, but iqdb.harry.lu is up and works in browser

### ISSUE THREAD

**Issue by giff-h** [jacklul/e621-Batch-Reverse-Search#5]

**Comment by jacklul** [comment]
Results page is stuck in infinite load, `curl` can't get result within timeout time, even when it reaches timeout and has part of the website data returned it will return false because it didn't finish loading.

iqdb.harry.lu has this issue from time to time, wait few days.

**Comment by jacklul** [comment]
Applied a workaround in updated version.
