### ISSUE TITLE
Duplicate printing of found match links

### ISSUE THREAD

**Issue by giff-h** [jacklul/e621-Batch-Reverse-Search#6]
1.1.9

When running the batch process, the output prints all the found links so far, including previous images in the batch process. The `found/links.html` is fine, it's only showing links associated with each image.

It also prints empty links for what I presume are unmatched files, they're not showing up in `found/`

**Comment by jacklul** [comment]
It shouldn't output empty links, can I see any example of the issue / screenshot?

**Comment by giff-h** [comment]
My screen recording is kinda fucked up at the moment, here's the best I could do:
https://photos.app.goo.gl/WPEcEDcBYEgOdh3f2

**Comment by jacklul** [comment]
Should be fixed!
