### ISSUE TITLE
fatal libpng error: Read Error: truncated data

### ISSUE THREAD

**Issue by ghost** [jacklul/e621-Batch-Reverse-Search#7]
`PHP Fatal error: imagecreatefrompng(): fatal libpng error: Read Error: truncated data in phar:///media/pictures/gayfurries/e6brs/e6BRS.phar/app.php on line 743`

This error appeared after picture 541/1671 of a Tumblr rip I did on my blog. The picture that it threw this error on is in fact truncated, hence the error message, but isn't there a fail-safe that can be implicated to work around this? Had I not been at my computer while this was running, I would've come back hours later to realize that the tool had thrown an error message hours before.

**Comment by jacklul** [comment]
@Youboontoo There wasn't any fail-safe because I didn't know about this issue before, all errors from 'imagecreate' were warnings for me.

Will apply a fix soon.

**Comment by ghost** [comment]
The same error is occurring, even after updating the script:
```
[1/1131] Searching 'tumblr_oves74yED51tek5qpo1_raw.png':
Trying md5 sum... no matching posts found!
Trying reverse search...PHP Fatal error: imagecreatefrompng(): gd-png: fatal libpng error: Read Error: truncated data in phar:///media/pictures/gayfurries/e6brs/e621BRS.phar/app.php on line 744
```
However, I think the `gd-png` part is new... Lemme check if all my binaries are up to date.

**Comment by ghost** [comment]
Nope, everything is up to date.

uname -a:
`Linux tux-server 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tues Oct 10 16:30:51 UTC 2017 i686 i686 i686 GNU/Linux`

php -v:
`PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )`

**Comment by jacklul** [comment]
@Youboontoo Can I have the problematic image so I can test it?

**Comment by Youboontoo** [comment]
From what it looks like before the truncation, it is an NSFW picture so beware.
[https://imgur.com/a/aovVC](https://imgur.com/a/aovVC)

**Comment by ghost** [comment]
![tumblr_oves74yed51tek5qpo1_raw](https://user-images.githubusercontent.com/16302135/32572577-e2811162-c47f-11e7-8497-93ba91de2ae3.png)

Like I mentioned earlier, the picture is in fact truncated, so that's what is causing this issue.

**Comment by jacklul** [comment]
@Youboontoo I Googled a bit and it seems to be some kind of bug in PHP on Linux, could you try with PHP 5.6?
This issue does not happen for me on Windows PHP 5.6 and 7.1.

Also, remember you can use config variable `USE_CONVERSION=false` to prevent conversion before uploading, this will get rid of the issue but slow down uploads (unless you have beast upload speed).

**Comment by ghost** [comment]
As soon as I get back home, I'll roll back to php5.6 and see if the issue
is resolved. If all else fails, I'll try it on my Windows box.

On Nov 8, 2017 12:31 PM, "jacklul" <notifications@github.com> wrote:

@Youboontoo <https://github.com/youboontoo> I Googled a bit and it seems to
be some kind of bug in PHP on Linux, could you try with PHP 5.6?
This issue does not happen for me on Windows PHP 5.6 and 7.1.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jacklul/e621-Batch-Reverse-Search/issues/7#issuecomment-342949905>,
or mute the thread

**Comment by ghost** [comment]
Rolling back now, will post results shortly

**Comment by ghost** [comment]
php -v:
`PHP 5.6.32-ubuntu16.04.1+deb.sury.org+1 (cli)`

Error message is still same as above, will test on Windows next.

**Comment by ghost** [comment]
Windows does not reproduce the same error message.

```
[1051/1131] Searching 'tumblr_oves74yED51tek5qpo1_raw.png':
 Trying md5 sum... no matching posts found!
 Trying reverse search... error: cannot create JPEG - expected resource input
```

Perhaps with the Linux script, you could try using `ImageMagick` to convert the pictures? I believe IM has more tolerance for corrupted pictures.

**Comment by jacklul** [comment]
Applied a workaround and tested it on [Windows Subsystem for Linux](https://msdn.microsoft.com/en-us/commandline/wsl/about), seems to work fine.

**Comment by ghost** [comment]
I can confirm that this fixed the issue. Thanks for your patience.
